"""relation docente seccion

Revision ID: 22ad9f446db6
Revises: 29e9080c7024
Create Date: 2026-05-14 09:24:15.682374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22ad9f446db6'
down_revision = '29e9080c7024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('secciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('docente_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'docentes', ['docente_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('secciones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('docente_id')

    # ### end Alembic commands ###
