"""motor pedagogico curricular

Revision ID: 50fafe84b2e0
Revises: a9b2a10a4e51
Create Date: 2026-05-27 11:47:43.070506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50fafe84b2e0'
down_revision = 'a9b2a10a4e51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resultados_analisis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacidad_curricular', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('desempeno_curricular', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('nivel_logro', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('recomendacion_curricular', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('coincidencia_modelo', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('paso_error_modelo', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('procedimiento_detectado', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resultados_analisis', schema=None) as batch_op:
        batch_op.drop_column('procedimiento_detectado')
        batch_op.drop_column('paso_error_modelo')
        batch_op.drop_column('coincidencia_modelo')
        batch_op.drop_column('recomendacion_curricular')
        batch_op.drop_column('nivel_logro')
        batch_op.drop_column('desempeno_curricular')
        batch_op.drop_column('capacidad_curricular')

    # ### end Alembic commands ###
