"""detalle procedimiento

Revision ID: 594f31bd8d78
Revises: ab0143f5ab47
Create Date: 2026-05-21 19:12:47.569416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '594f31bd8d78'
down_revision = 'ab0143f5ab47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resultados_analisis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detalle_procedimiento', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resultados_analisis', schema=None) as batch_op:
        batch_op.drop_column('detalle_procedimiento')

    # ### end Alembic commands ###
