"""actualizar examen alumno

Revision ID: 5a5395363745
Revises: e05b5084aad2
Create Date: 2026-05-18 11:09:52.152112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a5395363745'
down_revision = 'e05b5084aad2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('examenes_alumno', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ruta_imagen', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('texto_ocr', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('uso_modelo', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('estado_ocr', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('examenes_alumno', schema=None) as batch_op:
        batch_op.drop_column('estado_ocr')
        batch_op.drop_column('uso_modelo')
        batch_op.drop_column('texto_ocr')
        batch_op.drop_column('ruta_imagen')

    # ### end Alembic commands ###
