"""update resultado analisis

Revision ID: 7da6160bf71c
Revises: 8ac451128cab
Create Date: 2026-05-12 17:09:40.850571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7da6160bf71c'
down_revision = '8ac451128cab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resultados_analisis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('severidad_error', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('tema_matematico', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tipo_ejercicio', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('dificultad', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('pasos_estimados', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('riesgo_academico', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('tendencia_aprendizaje', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('perfil_matematico', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ruido_ocr', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('autocorreccion_aplicada', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resultados_analisis', schema=None) as batch_op:
        batch_op.drop_column('autocorreccion_aplicada')
        batch_op.drop_column('ruido_ocr')
        batch_op.drop_column('perfil_matematico')
        batch_op.drop_column('tendencia_aprendizaje')
        batch_op.drop_column('riesgo_academico')
        batch_op.drop_column('pasos_estimados')
        batch_op.drop_column('dificultad')
        batch_op.drop_column('tipo_ejercicio')
        batch_op.drop_column('tema_matematico')
        batch_op.drop_column('severidad_error')

    # ### end Alembic commands ###
