"""nucleo inteligente tamara

Revision ID: 8ac451128cab
Revises: 53c065521b74
Create Date: 2026-05-12 14:00:10.377601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ac451128cab'
down_revision = '53c065521b74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('bimestre', sa.Integer(), nullable=False),
    sa.Column('unidad', sa.Integer(), nullable=False),
    sa.Column('tipo_evaluacion', sa.String(length=50), nullable=False),
    sa.Column('fecha_evaluacion', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('docente_id', sa.Integer(), nullable=False),
    sa.Column('grado_id', sa.Integer(), nullable=False),
    sa.Column('seccion_id', sa.Integer(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['docente_id'], ['docentes.id'], ),
    sa.ForeignKeyConstraint(['grado_id'], ['grados.id'], ),
    sa.ForeignKeyConstraint(['seccion_id'], ['secciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ejercicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('enunciado', sa.Text(), nullable=False),
    sa.Column('tipo_ejercicio', sa.String(length=100), nullable=False),
    sa.Column('competencia', sa.String(length=150), nullable=False),
    sa.Column('nivel_dificultad', sa.String(length=50), nullable=True),
    sa.Column('puntaje', sa.Float(), nullable=True),
    sa.Column('respuesta_correcta', sa.Text(), nullable=True),
    sa.Column('procedimiento_modelo', sa.Text(), nullable=True),
    sa.Column('imagen_modelo', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('evaluacion_id', sa.Integer(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['evaluacion_id'], ['evaluaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('examenes_alumno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('porcentaje_analisis', sa.Float(), nullable=True),
    sa.Column('precision_ocr', sa.Float(), nullable=True),
    sa.Column('fecha_procesamiento', sa.DateTime(), nullable=True),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('evaluacion_id', sa.Integer(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], ),
    sa.ForeignKeyConstraint(['evaluacion_id'], ['evaluaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('respuestas_alumno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imagen_respuesta', sa.String(length=255), nullable=False),
    sa.Column('texto_ocr', sa.Text(), nullable=True),
    sa.Column('expresion_detectada', sa.Text(), nullable=True),
    sa.Column('expresion_normalizada', sa.Text(), nullable=True),
    sa.Column('estado_ocr', sa.String(length=30), nullable=True),
    sa.Column('precision_ocr', sa.Float(), nullable=True),
    sa.Column('observaciones_ocr', sa.Text(), nullable=True),
    sa.Column('ejercicio_id', sa.Integer(), nullable=False),
    sa.Column('examen_alumno_id', sa.Integer(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ejercicio_id'], ['ejercicios.id'], ),
    sa.ForeignKeyConstraint(['examen_alumno_id'], ['examenes_alumno.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resultados_analisis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expresion_original', sa.Text(), nullable=True),
    sa.Column('expresion_procesada', sa.Text(), nullable=True),
    sa.Column('expresion_sympy', sa.Text(), nullable=True),
    sa.Column('es_correcto', sa.Boolean(), nullable=True),
    sa.Column('porcentaje_coincidencia', sa.Float(), nullable=True),
    sa.Column('tipo_error', sa.String(length=100), nullable=True),
    sa.Column('descripcion_error', sa.Text(), nullable=True),
    sa.Column('recomendacion', sa.Text(), nullable=True),
    sa.Column('nivel_confianza', sa.Float(), nullable=True),
    sa.Column('estado_analisis', sa.String(length=30), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('respuesta_alumno_id', sa.Integer(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['respuesta_alumno_id'], ['respuestas_alumno.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('respuesta_alumno_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resultados_analisis')
    op.drop_table('respuestas_alumno')
    op.drop_table('examenes_alumno')
    op.drop_table('ejercicios')
    op.drop_table('evaluaciones')
    # ### end Alembic commands ###
