"""add procedimiento_modelo

Revision ID: a9b2a10a4e51
Revises: 594f31bd8d78
Create Date: 2026-05-25 15:47:06.474959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9b2a10a4e51'
down_revision = '594f31bd8d78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('procedimiento_modelo', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluaciones', schema=None) as batch_op:
        batch_op.drop_column('procedimiento_modelo')

    # ### end Alembic commands ###
