"""ejercicio opcional en respuesta alumno

Revision ID: ab0143f5ab47
Revises: c5dcd968cbb6
Create Date: 2026-05-20 19:52:50.672074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab0143f5ab47'
down_revision = 'c5dcd968cbb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('respuestas_alumno', schema=None) as batch_op:
        batch_op.alter_column('ejercicio_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('respuestas_alumno', schema=None) as batch_op:
        batch_op.alter_column('ejercicio_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
