"""modelo evaluacion

Revision ID: c5dcd968cbb6
Revises: 5a5395363745
Create Date: 2026-05-18 12:33:34.179449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5dcd968cbb6'
down_revision = '5a5395363745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('respuesta_modelo', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ruta_modelo', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluaciones', schema=None) as batch_op:
        batch_op.drop_column('ruta_modelo')
        batch_op.drop_column('respuesta_modelo')

    # ### end Alembic commands ###
