"""agregar competencia y fase polya

Revision ID: e05b5084aad2
Revises: bec7f70ebec3
Create Date: 2026-05-14 14:17:49.472742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e05b5084aad2'
down_revision = 'bec7f70ebec3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resultados_analisis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('competencia', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('fase_polya', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resultados_analisis', schema=None) as batch_op:
        batch_op.drop_column('fase_polya')
        batch_op.drop_column('competencia')

    # ### end Alembic commands ###
